# Generated by Django 5.2.7 on 2025-11-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('src', models.CharField(db_index=True, max_length=64, verbose_name='src')),
                ('dst', models.CharField(db_index=True, max_length=64, verbose_name='dst')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='duration')),
                ('billsec', models.PositiveIntegerField(default=0, verbose_name='billsec')),
                ('disposition', models.CharField(max_length=32, verbose_name='disposition')),
                ('answered', models.BooleanField(default=False, verbose_name='answered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Call record',
                'verbose_name_plural': 'Call records',
                'ordering': ('-calldate',),
                'unique_together': {('calldate', 'src', 'dst')},
            },
        ),
    ]
