# Generated by Django 5.2.7 on 2025-11-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together=set(),
        ),
    ]
