# Generated by Django 5.2.7 on 2025-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_callrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='disposition',
            field=models.CharField(choices=[('ANSWERED', 'Answered'), ('ANSWER', 'Answer'), ('OTHER', 'Other')], default='OTHER', max_length=32, verbose_name='disposition'),
        ),
    ]
