# Generated by Django 5.2.7 on 2025-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_callrecord_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='disposition',
            field=models.CharField(choices=[('ANSWERED', 'Answered'), ('NO ANSWER', 'No Answer'), ('OTHER', 'Other')], default='NO ANSWER', max_length=32, verbose_name='disposition'),
        ),
    ]
