# Generated by Django 5.2.7 on 2025-11-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_callrecord_disposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ('-calldate',), 'verbose_name': 'Csv Данный', 'verbose_name_plural': 'Csv Данные'},
        ),
    ]
